server:
  port: 8082

spring:
  application:
    name: customer-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/shopizer}
